config/routes.rb
Rails.application.routes.draw do

  root to: 'cocktails#index'

  # delete 'doses/:id', to: 'doses#destroy'
  resources :doses, only: [:destroy]

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
    @cocktail_new = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = Cocktail.find(@dose.cocktail.id)
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="add-new-cocktail" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="exampleModalLabel">Add new cocktail 😋</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <%= simple_form_for @cocktail_new do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Create cocktail", class: "btn btn-lg btn-outline-primary" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<% bg = ["#398BCB", "#31D8B4", "#F9C55F", "#8F5FA8", "#F0796A"] %>

<div class="banner-container">
  <h1><span id="banner-typed-text"></span></h1>
  <br>
<button type="button" class="btn btn-lg btn btn-outline-primary" data-toggle="modal" data-target="#add-new-cocktail">
  Add new cocktail
</button>
</div>

<%= render 'modal' %>

<div class="cards">
  <% @cocktails.each do |c| %>
  <% unless c.photo.nil? %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.1)),
         url('<%= cl_image_path c.photo%>')">
  <% end %>
    <%= c.name %>
    <%= link_to cocktail_path(c) do %>
    <span id="card-link"></span>
    <% end %>
  </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<h1>Add a new cocktail</h1>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Create cocktail", class: "btn btn-lg btn-outline-success" %>
  <%= link_to "Back to cocktails", cocktails_path, class: "btn btn-lg btn-outline-danger" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo%>');">
  <h1><%= @cocktail.name %></h1>
</div>

<div style="text-align: center; margin-bottom: 15px;">
  <%= link_to "Add dose", new_cocktail_dose_path(@cocktail), class: "btn btn-lg btn-outline-success" %>
  <%= link_to "Back to cocktails", cocktails_path, class: "btn btn-lg btn-outline-danger" %>
</div>

<% @cocktail.doses.each_with_index do |dose, index| %>
<ul class="list-group list-group-flush">
  <li class="list-group-item"><strong>Step <%= index + 1 %> <%= link_to "🗑", dose_path(dose), method: :delete %></strong></li>
  <li class="list-group-item"><%= dose.description %></li>
  <li class="list-group-item"><%= dose.ingredient.name %></li>
</ul>
<% end %>

app/views/doses/new.html.erb
<h1>Add dose to <%= @cocktail.name %></h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "Add dose", class: "btn btn-lg btn-outline-danger" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy cocktails 😜</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="col-8 col-centered">
      <%= yield %>
      </div>
      <%= javascript_include_tag "application" %>
      <%= javascript_pack_tag "application" %>
    </div>
  </body>
</html>